### ISSUE TITLE
Impossible to make it work

### ISSUE THREAD

**Issue by OtterHacker** [mandiant/ADFSpoof#11]
Look like the use of an unstable and unmaintain fork of cryptography shows its limit. 
It's impossible to build the fork with OpenSSL3.0 which is now the default version installed.
It's a pity

**Comment by szymex73** [comment]
The custom version of cryptography wasn't necessary, I made a fork of the repo [here](https://github.com/szymex73/ADFSpoof) where the custom kbkdf function is implemented separately of the crypto lib allowing it to use the latest version of cryptography (or at least much more recent, haven't tested it recently).

**Comment by OtterHacker** [comment]
Nice ! I had to spawn a Debian 9 just to make it work ^^ Will look at your repo !

**Comment by Iansus** [comment]
Optionally, you can find a working (but dirty) Dockerfile below, which uses a fork of cryptography to make it work

```
FROM debian:buster

RUN apt update
RUN apt install -y --force-yes python3 python3-pip unzip git
RUN git clone https://github.com/mandiant/ADFSpoof
RUN python3 -m pip install -U setuptools
RUN cd ADFSpoof && sed -i 's/dev1/1/g' requirements.txt && python3 -m pip install -r requirements.txt -v
RUN python3 -m pip uninstall cryptography
RUN apt install libffi-dev
RUN apt install libssl-dev
RUN python3 -m pip install git+https://github.com/dmb2168/cryptography

CMD ["sleep","infinity"]
```

The Dockerfile only sets up the environment, making the program run on your inputs is at the user's discretion.

**Comment by dmb2168** [comment]
Closing this issue thanks to @szymex73  merge request
