### ISSUE TITLE
Getting error while installing "pip install -r requirements.txt"

### ISSUE THREAD

**Issue by HemantRajpal-9018** [mandiant/ADFSpoof#5]
Running setup.py install for restructuredtext-lint ... done
  Running setup.py develop for cryptography
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\hemant\appdata\local\programs\python\python39\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Hemant\\Downloads\\cryptography-master\\cryptography-master\\setup.py'"'"'; __file__='"'"'C:\\Users\\Hemant\\Downloads\\cryptography-master\\cryptography-master\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps
         cwd: C:\Users\Hemant\Downloads\cryptography-master\cryptography-master\
    Complete output (20 lines):
    running develop
    running egg_info
    writing src\cryptography.egg-info\PKG-INFO
    writing dependency_links to src\cryptography.egg-info\dependency_links.txt
    writing requirements to src\cryptography.egg-info\requires.txt
    writing top-level names to src\cryptography.egg-info\top_level.txt
    reading manifest file 'src\cryptography.egg-info\SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    no previously-included directories found matching 'docs\_build'
    warning: no previously-included files matching '*' found under directory 'vectors'
    writing manifest file 'src\cryptography.egg-info\SOURCES.txt'
    running build_ext
    generating cffi module 'build\\temp.win-amd64-3.9\\Release\\_padding.c'
    creating build
    creating build\temp.win-amd64-3.9
    creating build\temp.win-amd64-3.9\Release
    generating cffi module 'build\\temp.win-amd64-3.9\\Release\\_constant_time.c'
    generating cffi module 'build\\temp.win-amd64-3.9\\Release\\_openssl.c'
    building '_openssl' extension
    error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\users\hemant\appdata\local\programs\python\python39\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Hemant\\Downloads\\cryptography-master\\cryptography-master\\setup.py'"'"'; __file__='"'"'C:\\Users\\Hemant\\Downloads\\cryptography-master\\cryptography-master\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.

**Comment by HemantRajpal-9018** [comment]
on my other machine,I have even installed Microsoft Visual C++ , OpenSSL, rush, setting environment variables , installing all dependencies , also tried testing and making changes in setup.py file and pyproject.toml files but still got no luck. KIndly guide through this as i have installed this package on my mac os but it's not happening in windows. 
![Capture](https://user-images.githubusercontent.com/71565751/111351948-10162f00-865a-11eb-83a2-af437efbbc60.JPG)

**Comment by dmb2168** [comment]
This should be fixed now - the latest commit does away with the custom cryptographu requirement
